#!/bin/sh

printf "### One Key Kernel Module Init Starting... ###\n"
module="ok_crypto"
device="ok_crypto"
mode="664"

while [ $# -gt 0 ]
do
    case $1 in
        -r|r|--remove|stop|exit|quit)
            printf "removing $device from /dev\n"
            rmmod $module || exit 1
            rm -f /dev/${device}*
            printf "remove done\n"
            exit 0
            ;;
        start|restart)
            printf "initing $module and add /dev/$device\n"
            ;;
        *)
            ;;
    esac
    shift 
done
# invoke insmod with all arguments we got
# and use a pathname, as newer modutils don't look in . by default
/sbin/insmod ./$module.ko $* || exit 1
# remove stale nodes
rm -f /dev/${device}[0-3]
major=$(awk -v tmp="$module" '$2==tmp { print $1}' /proc/devices)
mknod /dev/${device}0 c $major 0
mknod /dev/${device}1 c $major 1
mknod /dev/${device}2 c $major 2
mknod /dev/${device}3 c $major 3
# give appropriate group/permissions, and change the group.
# Not all distributions have staff, some have "wheel" instead.
group="staff"
grep -q '^staff:' /etc/group || group="wheel"
chgrp $group /dev/${device}[0-3]
chmod $mode  /dev/${device}[0-3]
printf "### One Key Kernel Module Init Done! ###\n"
